export default {
  primary: "purple",
  secondary: "green",
  error: "red"
  //   background: 'purple',
  //   surface: 'purple',
  //   primaryBg: 'purple',
  //   secondaryBg: 'purple',
  //   textPrimaryOnBackground: 'purple',
  //   textSecondaryOnBackground: 'purple',
  //   textHintOnBackground: 'purple',
  //   textDisabledOnBackground: 'purple',
  //   textIconOnBackground: 'purple',
  //   textPrimaryOnLight: 'purple',
  //   textSecondaryOnLight: 'purple',
  //   textHintOnLight: 'purple',
  //   textDisabledOnLight: 'purple',
  //   textIconOnLight: 'purple',
  //   onPrimary: 'purple',
  // onSecondary: 'purple',
  // onError: 'purple',
  // textPrimaryOnDark: 'purple',
  // textSecondaryOnDark: 'purple',
  // textHintOnDark: 'purple',
  // textDisabledOnDark: 'purple',
  // textIconOnDark: 'purple',
};
